'$schema' = 'https://starship.rs/config-schema.json'

continuation_prompt = '▶▶'

[character]
success_symbol = '[➜](bold green)'

[username]
style_user = 'bold green'
style_root = 'bold black'
format = '[$user]($style)@'
disabled = false
show_always = true

[directory]
style = 'bold blue'
home_symbol = '🏠'

[git_status]
conflicted = '🚩'
untracked = '✨'
staged = '[++\($count\)](green)'

[time]
disabled = false
style = 'bold white'
