name: vscode-marketplace

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: latest
            - run: npm run prepublish
            - name: Publish to VSCode Marketplace
              uses: HaaLeo/publish-vscode-extension@v1
              with:
                  pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
                  registryUrl: https://marketplace.visualstudio.com
